[tools]
go = "1.27.1"

[env]
_.path = ["{{config_root}}/bin"]

[tasks.test]
run = "go test ./..."

[tasks.service]
run = "go run ./cmd/service"
env = { _.file = ".env" }

[tasks.build]
run = "go build -o bin/service ./cmd/service"
